name: recipebook
description: A Flutter app to display recipes with details.
publish_to: "none" # Prevent accidental publishing
version: 1.0.0+1

environment:
  sdk: ">=3.10.0-162.1.beta <4.0.0"
  flutter: ">=3.37.0-0.1.pre"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/chicken_quesadilla.jpg
    - assets/images/avocado_toast.jpg
    - assets/images/garlic_butter_shrimp.jpg
